### ISSUE TITLE
Soundtouch plugin will not launch on Synology NAS "Error: Can not find module"

### ISSUE THREAD

**Issue by Seger85** [Adeptive/homebridge-soundtouch#17]
[marcoraddatz-homebridge1.zip](https://github.com/CONNCTED/homebridge-soundtouch/files/1602115/marcoraddatz-homebridge1.zip)

[config and install.zip](https://github.com/CONNCTED/homebridge-soundtouch/files/1602133/config.and.install.zip)

Hello everybody,

Unfortunately my English is pretty bad, so I write in German:
I have not started the soundtouch plugin for quite some time, or will not start the entire homebridge once I integrate the soundtouch plugin into the install.sh and the config.json.

It always comes the error that the plugin is not found, the same phenomenon I get on the https://npm.runkit.com/homebridge-soundtouch test page.

I use the Homebridge in the Docker.

Other plugins work 100% like e.g. Harmony and Homematic.
Nodeversion I have already tested all.

Is it due to the plugin or is the error to look for me?
If the problem lies with me, I would be glad if someone can help me (please very simple, I am not quite so fit in the topic - like also by Teamviewer).

I uploaded a LOG from the Docker.

thank you for your help

Seger

Hallo zusammen,

mein Englisch ist leider ziemlich schlecht, daher schreibe ich zusätzlich auf Deutsch:
Ich bekomme das Soundtouch Plugin seit geraumer Zeit nicht mehr gestartet bzw. startet die gesamte Homebridge nicht mehr sobald ich das Soundtouch Plugin in die install.sh und die config.json integriere.

Es kommt immer der Fehler das das Plugin nicht gefunden wird, das selbe Phänomen bekomme ich auch auf der https://npm.runkit.com/homebridge-soundtouch Testseite.

Ich benutze die Homebridge im Docker.

Andere Plugins funktionieren zu 100% wie z.B. Harmony und Homematic.
Nodeversionen habe ich bereits alle durchgetestet.

Liegt es am Plugin oder ist der Fehler doch bei mir zu suchen?
Wenn das Problem bei mir liegt würde ich mich freuen wenn mir jemand helfen kann (bitte sehr einfach, bin nicht ganz so fit in dem Thema - gerne auch per Teamviewer).

Ich habe ein LOG aus dem Docker mit hochgeladen.

**Comment by Seger85** [comment]
By other comments, I see that it works on some, maybe someone can tell me what I'm doing wrong?

Thanks and best regards
Seger

**Comment by geertsmichael** [comment]
It's very hard to check this huge log file for the root cause. 
Can you delete the log file, just start homebridge once and export the log file so it only contains the bare minimum.

Also to be sure, is the name of your SoundTouch device "Radio Küche" and "Radio Schlafzimmer"?
To check this, you need to open the Bose SoundTouch app and verify the name of your speaker. This need to match with the "room" property in the config.json file.

Are you sure your docker container is configured from a network point of view, so it can access your local network and can access the SoundTouch devices?

**Comment by Seger85** [comment]
[Config und Install file.zip](https://github.com/CONNCTED/homebridge-soundtouch/files/1608802/Config.und.Install.file.zip)
Hey,

First of all thank you for looking at everything and trying to help me. It is strange that I used the plugin felt 7 months and then it sometime did not go with the described error. Why is there always this message that a module was not found, even on the test page where you can go through the plugin?

I have the names exactly as stated in the config file, I upload again a screenshot of the Bose app with high. Could it possibly be that I have a Node / npm problem on my Synolgy? But actually everything is controlled by the Docker and the Homebridge and there everything is fine.

I have the log file again set up, maybe you'll find something there.

Maybe you can help me with a Teamviever?

In order to exclude the topic with Node / npm etc., I can somehow delete the Synolgy Node folder or rebuild it, or am I not on the right way.

Thanks for your feedback and your great help!

Best regards
Seger
![bose1](https://user-images.githubusercontent.com/35084198/34640202-8e756f26-f2ee-11e7-9f1f-d79443d308e1.PNG)
![bose2](https://user-images.githubusercontent.com/35084198/34640203-8e8c45f2-f2ee-11e7-9ad8-4a714bd88b7c.PNG)
![log1](https://user-images.githubusercontent.com/35084198/34640204-8ea267f6-f2ee-11e7-926a-ab0fa22fbd40.PNG)
![log2](https://user-images.githubusercontent.com/35084198/34640205-8eb94c64-f2ee-11e7-930b-f1e0cf7b56ab.PNG)

**Comment by geertsmichael** [comment]
This errors happens when starting homebridge.

Can you send me the log files when executing a `npm install -g homebridge-soundtouch`?
I assume that install failed, resulting in the fact that your homedbridge server doesn't start.

You can always delete the node_modules folder and try to nom install again.
You can also uninstall first before trying installing again, by executing: `npm uninstall -g homebridge-soundtouch`

What is your version of node and nom? (can be checked by running `npm --version` and `node --version`

**Comment by Seger85** [comment]
![screenshot](https://user-images.githubusercontent.com/35084198/34644561-3fdc6fcc-f339-11e7-82c2-db98bfd81a1c.PNG)


Hey you, maybe you just want to teamviever on my calculator?

Unfortunately, I can not send you a small log from the Docker, the Docker always creates a log per day and that is totally long and includes tests on my part. Unfortunately, I can not reset the protocol in Docker. So that's not going to do much for sure.

I have the orders times per putty connection executed. The user seger is admin, but something does not seem to work for your plugin / my rights. I hope you know what to do with the screenshot. Otherwise I'll try again later with the log.

Teamviever ID 830 937 130 (if required)

Many thanks
Seger

**Comment by Seger85** [comment]
Hey you,

did you already have time to look at my problem? I have no plan at all where I could start like. I would be very happy about your next suport.

Many greetings and heartfelt thanks
Seger

**Comment by Seger85** [comment]
Push :) do you have a new News for me?

Thanks so lot
Seger
